### ISSUE TITLE
Improving the module system

### ISSUE THREAD

**Issue by astralien3000** [AversivePlusPlus/AversivePlusPlus#20]
Currently, the modules are separated, but unable to be compiled as standalone, and the dependency management is not good (you need to add the modules in a particular order to be compiled correctly).

The fact is CMake is not good a doing this. But I have found a package manager that can be integrated to our current build chain, and simplify it a lot : [conan](https://github.com/conan-io/conan).

I think it is worth to at least try to make every modules as a conan package (see the branch dev-conan in each module).

Tasks: 
- [x] Make every module a conan package
- [x] Make the whole library a conan package
- [x] Tests/debugs

**Comment by Elioty** [comment]
I heard about conan, in a good way! We can give it a try ;)

**Comment by astralien3000** [comment]
Cool !
The problem is that I need to pass the information of target (mcu/native/etc...) across the modules, which I can do (easily) in a "custom way" with the current conan, but I would like to help their project to have a standard way to do so.
That is what I discuss on [this issue](https://github.com/conan-io/conan/issues/86#issuecomment-224337160), if you want to take part.

**Comment by Elioty** [comment]
I read that other issue from conan repo, their project is cool AND they listen to feedbacks, how great :)

**Comment by astralien3000** [comment]
Here it is !
[All modules have been ported to conan](https://github.com/AversivePlusPlus/AversivePlusPlus/tree/dev-conan).

**Comment by astralien3000** [comment]
Done
